sudo: false
language: rust
#cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

matrix:
  include:
    - rust: nightly
      cache: false
      # FIXME: turn this back on when code coverage is enabled
      #sudo: required # Work around for travis-ci/travis-ci#9061
      env:
        - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size
      after_success:
        - ./ci/install-kcov.sh && ./ci/coverage.sh
    - rust: beta
    - rust: stable
    - os: osx
      rust: stable

branches:
  only:
    - master
    - /v?\d(\.\d)*/

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - (cd conch-runtime && cargo check --no-default-features)
  - cargo check --all-targets
    # Retry with fewer cores if the initial `cargo test` fails to work around possible OOM errors
    # for more details see https://github.com/rust-lang/cargo/issues/4415
  - cargo test --no-fail-fast ||
    (
      echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
      cargo test --no-fail-fast --verbose -j 1
    )

notifications:
  email:
    on_success: never
