sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

rust:
  - nightly
  - beta
  - stable
  - 1.19.0

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo build --no-default-features
  - cargo build
    # Retry with fewer cores if the initial `cargo test` fails to work around possible OOM errors
    # for more details see https://github.com/rust-lang/cargo/issues/4415
  - cargo test --no-fail-fast ||
    (
      echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
      cargo test --no-fail-fast --verbose -j 1
    )
  - cargo doc --no-deps
after_success:
  # NB: kcov only works on linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/install-kcov.sh && ./ci/coverage.sh; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size

notifications:
  email:
    on_success: never

os:
  - linux
  - osx
