sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

matrix:
  include:
    - rust: nightly
    - rust: beta
    - rust: stable
      after_success:
        - ./ci/install-kcov.sh && ./ci/coverage.sh
    - rust: 1.20.0
    - os: osx
      rust: stable

branches:
  only:
    - master
    - /v?\d(\.\d)*/

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo check --no-default-features
  - cargo build
    # Retry with fewer cores if the initial `cargo test` fails to work around possible OOM errors
    # for more details see https://github.com/rust-lang/cargo/issues/4415
  - cargo test --no-fail-fast ||
    (
      echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
      cargo test --no-fail-fast --verbose -j 1
    )
  - cargo doc --no-deps

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size

notifications:
  email:
    on_success: never
