sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

matrix:
  include:
    - rust: nightly
      cache: false
      sudo: required # Work around for travis-ci/travis-ci#9061
      env:
        - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size
      after_success:
        - ./ci/install-kcov.sh && ./ci/coverage.sh

    - rust: beta
    - rust: stable
    - rust: 1.26.0
    - os: osx
      rust: stable

branches:
  only:
    - master
    - /v?\d(\.\d)*/

before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo check --no-default-features
  - cargo check
    # Retry with fewer cores if the initial `cargo test` fails to work around possible OOM errors
    # for more details see https://github.com/rust-lang/cargo/issues/4415
  - cargo test --no-fail-fast ||
    (
      echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
      cargo test --no-fail-fast --verbose -j 1 ||
      # Travis has been consistently failing on macOS due to exhausting file descriptors
      # which causes the file test suites to fail (keeping in mind that tokio-core is spinning
      # up its own reactor file descriptor during each test which makes things worse).
      # To get around this we'll try to run the test cases with just a single thread.
      # FIXME(breaking): Once we've fully migrated off tokio-core and to tokio proper,
      # this can go away
      echo 'secondary `cargo test` failed, retrying with fewer cores and test threads' &&
      cargo test --no-fail-fast --verbose -j 1 -- --test-threads 1
    )

notifications:
  email:
    on_success: never
