[package]
name = "conch-runtime"
version = "0.1.0"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]

[dependencies]
conch-parser = { path = "../conch-parser" }
clippy      = { version = "~0.0.80", optional = true }
futures     = "0.1.14"
futures-cpupool = "0.1.2"
glob        = "0.2"
lazy_static = "0.2"
mio  = "0.6.2"
rental = "0.4.10"
tokio-core  = "0.1.4"
tokio-io = "0.1"
# FIXME: switch to "0.1.4" after it is published
tokio-process = { git = "https://github.com/alexcrichton/tokio-process.git" }
void = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys    = "0.2.1"
winapi          = "0.2.5"

[dev-dependencies]
tempdir = "0.3"
