[package]
name = "conch-runtime"
version = "0.1.0"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]

[dependencies]
clippy      = { version = "~0.0.80", optional = true }
futures     = "^0.1.7"
glob        = "0.2"
lazy_static = "0.2"
conch-parser = { path = "../conch-parser" }
tokio-core  = "0.1.3"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio  = "0.6.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys    = "0.2.1"
winapi          = "0.2.5"

[dev-dependencies]
tempdir = "0.3"
