[package]
name = "conch-runtime"
version = "0.1.5"
authors = ["Ivan Petkov <ivanppetkov@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ipetkov/conch-runtime"
homepage = "https://github.com/ipetkov/conch-runtime"
documentation = "https://docs.rs/conch-runtime/"
keywords = ["shell", "runtime"]
categories = ["asynchronous"]
description = """
A library for evaluating/executing programs written in the shell programming language.
"""

[features]
default = ["conch-parser", "top-level"]
top-level = ["conch-parser"]

[dependencies]
conch-parser = { version = "0.1", optional = true }
clap        = "2"
clippy      = { version = "~0.0.80", optional = true }
futures     = "0.1.14"
futures-cpupool = "0.1.2"
glob        = "0.2"
lazy_static = ">=0.2, <2"
mio  = "0.6.2"
rental = "0.4.10"
tokio-core  = "0.1.4"
tokio-io = "0.1"
tokio-process = "0.1.4"
void = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys    = "0.2.1"
winapi          = "0.2.5"

[dev-dependencies]
owned_chars = "0.2.1"
tempdir = "0.3"

[badges]
travis-ci = { repository = "ipetkov/conch-runtime" }
appveyor = { repository = "ipetkov/conch-runtime" }
is-it-maintained-issue-resolution = { repository = "ipetkov/conch-runtime" }
is-it-maintained-open-issues = { repository = "ipetkov/conch-runtime" }
codecov = { repository = "ipetkov/conch-runtime" }
